### PR TITLE
Check argument count for existence of optional table parameter

### LINKED ISSUE #6: Crash on init() with no parameter passed
Apologies, I introduced this bug.
The recently modified version of init() crashes if no options table is passed.

### PR DESCRIPTION
**Pull request by dri-richard**
Fixes #6

### CODE REVIEW

File: firebase/src/firebase.cpp [hunk 1]
```diff
@@ -63,7 +64,7 @@ static int Firebase_Init(lua_State* L) {
 	JNIEnv* env = 0;
 	dmGraphics::GetNativeAndroidJavaVM()->AttachCurrentThread(&env, NULL);
 	
-	if (lua_isnil(L, 1))
```
Comment (britzl) [inline firebase/src/firebase.cpp:66]: I think you could swap this for lua_isnoneornil(L, 1)

"Returns 1 if the given acceptable index is not valid (that is, it refers to an element outside the current stack) or if the value at this index is nil, and 0 otherwise."

**Review by britzl — CHANGES_REQUESTED** [review]
Perhaps use `lua_isnoneornil(L,1)` instead?

**Review by britzl — APPROVED** [review]
